// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWQXPULtlUAdrcL-VfigJZvf-e9VIsd8',
    appId: '1:843646198725:web:2e31bb4b70db773cc861ac',
    messagingSenderId: '843646198725',
    projectId: 'fixitparts-9a290',
    authDomain: 'fixitparts-9a290.firebaseapp.com',
    storageBucket: 'fixitparts-9a290.appspot.com',
    measurementId: 'G-5J5SNK0JFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ajviKMWQIzKJcJvblvs97YXtyLw_Ilg',
    appId: '1:843646198725:android:8def2e93eddcb34dc861ac',
    messagingSenderId: '843646198725',
    projectId: 'fixitparts-9a290',
    storageBucket: 'fixitparts-9a290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVegsJ2II7CCV8h30QuscA4eBV3ttEkFE',
    appId: '1:843646198725:ios:674904c04825c1b7c861ac',
    messagingSenderId: '843646198725',
    projectId: 'fixitparts-9a290',
    storageBucket: 'fixitparts-9a290.appspot.com',
    iosBundleId: 'com.fixitparts.fixitparts.fixitparts2',
  );
}
